### ISSUE TITLE
Compilation errors in space_border.c, function addNewBorder

### ISSUE THREAD

**Issue by DieterKoblenz** [aspace-sim/aspace#10]
`space_border.c: In function ‘addNewBorder’:
space_border.c:16:25: warning: unused parameter ‘executor’ [-Wunused-parameter]
 void addNewBorder(dbref executor, int border_number, const char* name, double radius, double x, double y, double z, char *buff, char **bp)
                         ^
space_border.c: In function ‘edit_border’:
space_border.c:102:24: warning: unused parameter ‘executor’ [-Wunused-parameter]
 void edit_border(dbref executor, int border_id, const char* setting, const char* new_value, char *buff, char **bp)
                        ^
space_border.c: In function ‘up_empire’:
space_border.c:224:9: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
         if (rr = fabs(-rr - (border->radius * border->radius))  < r ) {
         ^
space_border.c:240:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (get_random_long(1,100) < ((int) (sdb[x].sensor.lrs_signature
                                    ^
space_border.c:249:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (get_random_long(1,100) < ((int) (sdb[x].sensor.lrs_signature
                                  ^
`

**Comment by mike347** [comment]
All those warnings can be safely ignored. I have been meaning to clean up the code, as well as add support for universes (e.g. borders only appear in the specific universe they're assigned to).

I'll work on it this week.

**Comment by mike347** [comment]
Fixed by latest commits.
