### ISSUE TITLE
@space/makeship

### ISSUE THREAD

**Issue by pandasquee** [aspace-sim/aspace#12]
Hello,

Can someone please give me the accurate syntax for this? It's @space/makeship * named * in *

I have figured out that %0 is the dbref of the class %1 is the name of the ship but I cannot figure out what %2 (in *) is supposed to be. Can anyone help?

**Comment by ray73864** [comment]
The dbref# for where you want the space-object (in this case a ship) to be located.

Most mushes that use aspace would have a space-room such as #100 (Space Room), but space-objects can exist inside other space-objects (for the purposes of landing / docking), such as a ship landing on a planet or docking with a base.

Bases, planets and stars would generally be in the space room, ships would be on a planet, on another ship, or on a base, so the 'in *' could be 'in <spacen room>' or 'in <dbref# of planet / base / other ship>'.

**Comment by pandasquee** [comment]
Thank Ray - @space/makeship #201 named USS Faraday in #38

gives me

[Wizard Zone]--[Created USS Faraday(#262) with a class of Intrepid(#201) in Deep Space 11 using sdb 9 with a sdb read status of (0) and new bridge at #263]

**Comment by mloftis** [comment]
Just a fair warning that the soft code is a bit rough. F/ex no transporter implementation. No Comms - and part of the problem there is I'm pretty sure cdb (hardcode local_fun_cdb) is buggy/incomplete. (Like for no apparent reason I can fathom it loops and sets pe_regs 10x .... and that may be leaking memory). I...think it's also like ... really broke because it's got some misplaced {} maybe inside cdb()... part of the switch statement ends up inside the 't'ransmit case.

**Comment by ray73864** [comment]
CDB is fine in modern versions, I rewrote parts of it to fix issues with changes in Pennmush over the years.

Transporter has no actual implementation in hardcode beyond providing power, activating and deactivating the system, and that's about it, anything else it needs is pure softcode and games I guess will want to run it differently.

Communications, again is mostly softcode, CDB exists, has done for years, and Wayne@Paradox even released a compin system that utilises it at least 20yrs ago now (I think I even put it up here on the github?), but not every game wants to use CDB, and may choose to do it differently too.

But yes, the softcode itself is a mess, has been for years.
