### ISSUE TITLE
Landing/Docking Bay Doors

### ISSUE THREAD

**Issue by pandasquee** [aspace-sim/aspace#15]
This feature is undocumented and #38 starts with landing bay doors closed, so no good. I could not find in the source what they command syntax, nor could i find it looking through the console parents. Can someone point me to the right spot?

**Comment by mloftis** [comment]
All SC.  Nothing in the HC except the connected flag.

**Comment by pandasquee** [comment]
line 32 ``
						case 'u': switch (f4[0]) {``

ive been trying to figure out where exactly is calculated

**Comment by pandasquee** [comment]
Help from @mloftis
