### ISSUE TITLE
Makefile instructions need an update as most of the context is lost

### ISSUE THREAD

**Issue by Routhinator** [aspace-sim/aspace#18]
Hey there, just trying to follow your Makefile alteration instructions here in 2022, and the context from https://github.com/aspace-sim/aspace/wiki/Updating-Penn-Makefile seems to be lost.

There are a couple of points in the Pennmush Makefile that have a list of `.c` files now:

```make
hdrs/cmds.h: src/cmds.c src/command.c src/cque.c src/help.c src/set.c src/sql.c Patchlevel
	@PERL@ utils/mkcmds.pl commands

hdrs/switches.h: src/SWITCHES Patchlevel
	@PERL@ utils/mkcmds.pl switches

src/switchinc.c: src/SWITCHES Patchlevel
	@PERL@ utils/mkcmds.pl switches

hdrs/funs.h: src/fun*.c src/bsd.c src/conf.c src/extmail.c src/help.c src/markup.c src/wiz.c src/sql.c Patchlevel src/cque.c
	@PERL@ utils/mkcmds.pl functions
```

As a result I cannot be certain how to follow the first instruction.

There is no list of `*.o` files in the Makefile anymore, so the second instruction cannot be followed.

The last instruction says to add the blob to the end of the makefile, which would put it as part of the `htmldoc` make target - which doesn't seem correct either.

**Comment by ray73864** [comment]
You are looking at the wrong Makefile :)

The instructions specifically say to alter ```src/Makefile.in``` but you are looking at the Makefile.in in the Pennmush root directory.

**Comment by Routhinator** [comment]
... Oh. That makes sense. Sorry
